import React, { useState, useEffect } from 'react';
import { 
  ShoppingCart, 
  Users, 
  ArrowRight, 
  Sparkles, 
  CheckCircle2, 
  Clock, 
  Send,
  CreditCard,
  RefreshCw,
  Plus
} from 'lucide-react';

export default function BuyerLeadsView({ onRouteToPaymaster, onEventNotification }) {
  const [carts, setCarts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [customIntent, setCustomIntent] = useState('Procure 2 bags of light roast single origin for office filter brew');
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    loadCarts();
  }, []);

  const loadCarts = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/cart/list');
      const data = await res.json();
      setCarts(data.carts || []);
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreateCart = async () => {
    if (!customIntent) return;
    setIsGenerating(true);
    try {
      const res = await fetch('/api/cart/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          customer_intent: customIntent,
          agent_name: 'Custom AI Assistant',
        }),
      });
      const newCart = await res.json();
      setCarts([newCart, ...carts]);
      if (onEventNotification) {
        onEventNotification(`Created structured cart for: "${customIntent.substring(0, 40)}..."`);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 bg-white border border-slate-200 rounded-2xl shadow-xs">
        <div>
          <div className="flex items-center space-x-2 text-xs font-semibold text-blue-600 uppercase tracking-wider">
            <Users className="w-4 h-4" />
            <span>AI Buyer Pipeline</span>
          </div>
          <h2 className="text-xl font-bold text-slate-900 mt-0.5">
            Active Inbound AI Shopping Carts ({carts.length})
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Structured carts generated by autonomous shopping agents on behalf of end customers, waiting for payment authorization.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <span className="text-xs font-medium text-emerald-700 bg-emerald-50 px-3 py-1.5 rounded-xl border border-emerald-200">
            ✓ 100% TRAI & Consumer Protection Compliant
          </span>
        </div>
      </div>

      {/* Synthesize Cart Tester */}
      <div className="p-5 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-4">
        <div>
          <h3 className="text-sm font-bold text-slate-900 flex items-center space-x-2">
            <Sparkles className="w-4 h-4 text-blue-600" />
            <span>Simulate Customer Intent to Structured Cart</span>
          </h3>
          <p className="text-xs text-slate-500 mt-0.5">
            See how the Sales Agent takes conversational customer text and synthesizes a validated, machine-readable cart.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row items-center gap-2.5">
          <input
            type="text"
            value={customIntent}
            onChange={(e) => setCustomIntent(e.target.value)}
            placeholder="e.g. Buy 2 packs of specialty coffee for morning brew"
            className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-hidden focus:border-blue-500"
          />

          <button
            onClick={handleCreateCart}
            disabled={isGenerating}
            className="w-full sm:w-auto px-5 py-2 text-xs font-semibold bg-blue-600 hover:bg-blue-700 text-white rounded-xl shadow-xs transition-colors flex items-center justify-center space-x-1.5 cursor-pointer shrink-0"
          >
            {isGenerating ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Plus className="w-3.5 h-3.5" />}
            <span>Generate Cart</span>
          </button>
        </div>
      </div>

      {/* Cart Cards Grid */}
      {isLoading ? (
        <div className="p-12 bg-white border border-slate-200 rounded-2xl text-center text-xs text-slate-400">
          <RefreshCw className="w-6 h-6 animate-spin mx-auto text-blue-600 mb-2" />
          <span>Loading active buyer carts...</span>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {carts.map((cart) => (
            <div key={cart.id} className="p-5 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-4 flex flex-col justify-between hover:border-slate-300 transition-all">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-mono-code text-slate-400">Cart ID: {cart.id}</span>
                  <span className="text-[10px] font-medium text-blue-700 bg-blue-50 px-2 py-0.5 rounded-full border border-blue-100">
                    {cart.agent_name || 'AI Assistant'}
                  </span>
                </div>

                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Customer Intent</span>
                  <p className="text-xs font-semibold text-slate-900 mt-0.5 leading-relaxed">
                    "{cart.customer_intent}"
                  </p>
                </div>

                {/* Line Items */}
                <div className="p-3 bg-slate-50 rounded-xl border border-slate-100 space-y-1.5">
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Resolved Items</span>
                  {(cart.line_items || []).map((item, i) => (
                    <div key={i} className="flex items-center justify-between text-xs">
                      <span className="text-slate-700">{item.name || 'Specialty Coffee Item'} (x{item.quantity || 1})</span>
                      <span className="font-semibold text-slate-900 font-mono-code">₹{item.total || item.unit_price}</span>
                    </div>
                  ))}
                  <div className="pt-2 border-t border-slate-200/60 flex items-center justify-between text-xs font-bold text-slate-900">
                    <span>Total Amount</span>
                    <span className="font-mono-code text-blue-600">₹{cart.total_amount || cart.subtotal}</span>
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <button
                onClick={() => onRouteToPaymaster && onRouteToPaymaster(cart)}
                className="w-full py-2.5 px-4 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs shadow-xs transition-colors flex items-center justify-center space-x-1.5 cursor-pointer"
              >
                <CreditCard className="w-3.5 h-3.5" />
                <span>Route to Paymaster Checkout →</span>
              </button>
            </div>
          ))}
        </div>
      )}

    </div>
  );
}
